pipeline {
    agent any

    environment {
        BRANCH_NAME = "main"
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/savindu-pasintha/msdocs-python-flask-webapp-quickstart.git', branch: "${BRANCH_NAME}"
            }
        }
        
     
    }

    // post {
    //     always {
    //         // Clean up
    //         sh 'deactivate'
    //     }
    //     success {
    //         echo 'Pipeline completed successfully.'
    //     }
    //     failure {
    //         echo 'Pipeline failed.'
    //     }
    // }
}
