pipeline {
    agent any

    stages {
        stage('Trigger All Services') {
            parallel {
                stage('backend1 stage') {
                    steps {
                        script {
                            build job: 'backend1', wait: false
                        }
                    }
                }
                stage('frontend1 stage') {
                    steps {
                        script {
                            build job: 'frontend1', wait: false
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                // Custom post actions like cleanup
                echo 'Master pipeline completed.'
            }
        }
        success {
            echo 'All services triggered successfully.'
        }
        failure {
            echo 'One or more services failed to trigger.'
        }
    }
}
